INSERT INTO GameCategory (Title, Cname)
VALUES 

('ArmedForces.io','Action'),
('Capybara Click Pro', 'Idle'),
('Crazy Drifter','Racing'),
('Drift fury','Racing'),
('Drift Hunters Pro','Racing'),
('Drift King','Racing'),
('Drift Rider','Racing'),
('Edys Car Simulator','Racing'),
('Get On Top','Multiplayer'),
('Get On Top','Strategy'),
('GTA Simulator','Multiplayer'),
('Guerrillas','Shooting'),
('Highway Racer pro','Racing'),
('Highway Traffic','Racing'),
('Legendary Sniper','Shooting'),
('Love Tester','Girl Game'),
('Madalin Stunt cars Pro','Racing'),
('Masked Special forcec','Shooting'),
('Monster Truck Racing','Racing'),
('Police Chase Drifter','Racing'),
('Real Flight Simulator','Adventure'),
('Stuck fire Ball','Sport'),
('Stickman Destruction','Multiplayer'),
('Super Mini Racing','Racing');