ALTER TABLE GameCategory MODIFY COLUMN Cname VARCHAR(20);
ALTER TABLE GameCategory MODIFY COLUMN Title VARCHAR(30);
ALTER TABLE Ticket MODIFY TicketID INTEGER AUTO_INCREMENT;
ALTER TABLE Ticket MODIFY COLUMN Body VARCHAR(1024);
ALTER TABLE Ticket ADD COLUMN CreatedDate DATETIME;
ALTER TABLE Ticket ADD COLUMN Resolved BOOLEAN DEFAULT FALSE;