name: Format

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace --aosp"
          commit-message: "ci: Format code"
          github-token: ${{ secrets.PERSONAL_TOKEN }}
